class AboutController < ApplicationController
  def index
  end

  def team
    @team_members = [
      { image: asset_path('team/team_thumb_01.jpg'), imageRed: asset_path('team/team_thumb_01-red.jpg'), name:'Shabi Asghar', title: 'CEO', desc: 'With more than 28 years of experience in the mortgage industry, Shabi Asghar is dedicated to improving operations that deliver superior customer experience. At Commerce Home Mortgage Wholesale his progressive management style has created a work culture that empowers employees to deliver exceptional customer service. Asghar specializes in startups. A serial entrepreneur, he has launched and grown two of the largest publicly traded companies in the real estate lending industry, including an IPO that resulted in $750 million market capitalization within three years of launch. Currently Asghar serves as president of the Orange County chapter of the California Association of Mortgage Professionals (OCAMP). He graduated from California State University, Northridge, with a BS in Business Management.' },
      { image: asset_path('team/team_thumb_02.jpg'), imageRed: asset_path('team/team_thumb_02-red.jpg'), name:'Cindi Song', title: 'Vice President of Wholesale and Director of Operations ', desc: 'Cindi Song attended the University of Southern California with a BS in Business Administration. With over 20 years in the Mortgage Industry holding management positions in both Sales and Operations, the former Vice President of Retail Sales for Commerce Home Mortgage, launched the Wholesale Division to add another business channel to the Company. As her mission to be the industry leader of Jumbo Products, Song spearheaded the launch and success which is now Commerce Home Mortgage Wholesale. As Vice President and Director of Operations, she oversees the overall efficiency and the growth of the company while providing leadership and a corporate culture which is unparalleled in the industry. The culture encompasses that home and work are not mutually exclusive, promoting an exciting fast paced but family orientated environment with limitless opportunities. Her belief: People are the Company and what a great Company we have. '  },
      { image: asset_path('team/team_thumb_03.jpg'), imageRed: asset_path('team/team_thumb_03-red.jpg'), name:'Chi Do', title: 'Account Executive', desc: 'Chi Do works closely with customers to develop strategies that can lead to new sources of income, for them and for CHMW. In addition to explaining loan product features and benefits with new brokers, Chi Do ensures everyone is one the same page regarding the rules and regulations of the mortgage industry, and how brokers can operate successfully within the CHMW business model.  Chi enjoys traveling, exploring new places, and finding restaurants off the beaten track.' },
      { image: asset_path('team/team_thumb_04.jpg'), imageRed: asset_path('team/team_thumb_04-red.jpg'), name:'Gary Williamson', title: 'Account Executive', desc: 'In his role as Regional Sales Manager, Gary Williamson manages regional loan production, and oversees personal broker clients to ensure success from submission to funding. He loves the team atmosphere at CHMW, an opportunity to do business the right way, and building great relationships with his clients. In his spare time, Gary enjoys family activities, surfing, playing pick-up basketball games and running.' },
      { image: asset_path('team/team_thumb_05.jpg'), imageRed: asset_path('team/team_thumb_05-red.jpg'), name:'Dennis Taormina', title: 'Area Sales Manager', desc: 'Dennis Taormina’s main focus at CHMW is business-to-business sales, where he serves as the primary interface with brokers for the purpose of originating wholesale loans. Acting as the liaison between brokers and their staff, Dennis oversees the loan process from origination to funding.  Recognizing the potential for CHMW to be a major player in the wholesale mortgage industry, Dennis jumped at the opportunity to join a start up on the ground floor. Dennis enjoys scuba diving, snorkeling, jet skiing, body surfing and traveling to island destinations. When he’s not on the ocean, he can be found deep into books covering world history, politics, science, and philosophy.' },
      { image: asset_path('team/team_thumb_06.jpg'), imageRed: asset_path('team/team_thumb_06-red.jpg'), name:'Jill Glass', title: 'Area Sales Manager', desc: 'As Area Sales Manager, Jill Glass facilitates the business relationships between mortgage brokers and CHMW, with a special focus on training brokers and their teams on how to use the CHMW website to streamline the loan process. Jill works with clients in structuring and pricing loans, ensuring each broker receives exceptional customer service from inception to completion. Jill prides herself on presenting a professional image of the company to her brokers and processors.  A lover of the outdoors, Jill avidly pursues activities that offer an adrenaline rush, including boxing. Jill believes it is important to give back to her community, so she volunteers in projects that provide backpacks packed with food for under privileged school children.' },
      { image: asset_path('team/team_thumb_07.jpg'), imageRed: asset_path('team/team_thumb_07-red.jpg'), name:'John Reiher', title: 'Account Executive', desc: 'Area Sales Manager John Reiher acts as liaison between CHMW and brokers throughout all phases of the loan process. In addition he provides sales expertise, and solicits brokers for business in approved states. John is thrilled to have the opportunity to work for a company with drive and proven management in its early stages of growth. John enjoys spending time with his family and relaxing with a good football game on Sunday morning.' },
      { image: asset_path('team/team_thumb_08.jpg'), imageRed: asset_path('team/team_thumb_08-red.jpg'), name:'Nicole Kusano', title: 'Area Sales Manager', desc: 'Nicole Kusano’s watchword is “treat brokers like family.” As Area Sales Manager Nicole invites brokers to become part of the Commerce family. She provides service and support to brokers, assisting them in getting approved with Commerce, then training them on our portal, policy and procedures. Nicole manages the loan pipeline from origination to closing, ensuring all loans are complete and within guidelines. When guidelines or rates change, Nicole makes sure her brokers are kept in the know. The best part of her job, Nicole says, is providing the service that helps brokers develop and grow their business. For relaxation Nicole enjoys spending time at the beach with her family, traveling and baking.' },
      { image: asset_path('team/team_thumb_09.jpg'), imageRed: asset_path('team/team_thumb_09-red.jpg'), name:'Stephanie Cox', title: 'Area Sales Manager', desc: 'Stephanie Cox is responsible for facilitating, negotiating and executing broker agreements with approved partners. She also educates and trains all approved mortgage clients on CHMW’s lending policies, procedures, loan products and submission process. Stephanie joined CHMW because she believes their business model and streamlined underwriting system holds the potential to revolutionize the mortgage industry. As a team mom, Stephanie enjoys spending time with her kids, helping out their soccer practices, and volunteering as a religious education teacher in her community.' },
      { image: asset_path('team/team_thumb_10.jpg'), imageRed: asset_path('team/team_thumb_10-red.jpg'), name:'Michael Bennett', title: 'Area Sales Manager', desc: 'In his role as Area Sales Manager Michael Bennett guides new brokers and loan officers to CHMW.  Using face-to-face visits, video email, regular email, and good old phone calls Bennett works with brokers to assist them in funding mortgage loans for their clients. He ensures his clients understand the CHMW online system and our  process so that it is smooth and easy for the client.  With more than 20 years in the industry, Michael is inspired by the team at CHMW and the level of service they provide its broker clients. Along with his wife of 32 years, Michael runs a dog rescue also that specializes in puppies and their mothers.' }
    ]
  end

  def latest_news
  end

  def join_us
  end

  def contact_us
  end

  private

  def asset_path(asset_name)
    ActionController::Base.helpers.asset_path(asset_name)
  end

end
